### ISSUE TITLE
Add basic auth

### ISSUE THREAD

**Issue by Immortalin** [enricoros/big-AGI#146]
Add basic authentication to secure publicly exposed portals.

https://github.com/labd/nextjs-basic-auth-middleware

**Comment by tmikaeld** [comment]
Meanwhile, if you deployed to cloudflare, you can use their [Zero Trust Access Policies](https://developers.cloudflare.com/cloudflare-one/policies/access/policy-management/) to have a login screen for free.

**Comment by edmondop** [comment]
@Immortalin can you explain the use case here? Support for basic authentication seems to be a "development feature" rather than a production feature, since storing credentials safely requires a certain number of pre-cautions, such as salting them when writing to a database, securing the access to the database, implementing reset flows, etc.

Also, as @tmikaeld, one can place in front of the applicaiton an Oauth2 proxy using Okta for example using something like this: https://github.com/oauth2-proxy/oauth2-proxy


For production deployment, I think we should looking at providing OIDC, but that would only be worth if we are implementing also some sort of RBAC, which itself deserves some discussion.

**Comment by Immortalin** [comment]
The use case is for single user/family and friends deployment. For a single user i.e. deployed using Vercel, there just needs to be an easy way to not expose the app publicly.

**Comment by Immortalin** [comment]
Salting etc. are all easy to do, just provide a command line script to generate the hash and salt. Use `argon2` + `crypto.timingSafeEqual` for validation.

**Comment by edmondop** [comment]
> Salting etc. are all easy to do, just provide a command line script to generate the hash and salt. Use `argon2` + `crypto.timingSafeEqual` for validation.

I have looked in this issue more in depth, and I propose we create an issue [Epic] Authentication and we link basic and oauth as subissues. Also, it seems that Lucia would help to make both of them easy

**Comment by Immortalin** [comment]
Closed by [702e27e](https://github.com/enricoros/big-AGI/commit/702e27edbf854b6bd9a1e6177c3b33df7e398127)

**Comment by Immortalin** [comment]
@enricoros the [http basic auth](https://github.com/enricoros/big-AGI/blob/main/middleware_BASIC_AUTH.ts) should probably use [`timingSafeEqual`](https://developers.cloudflare.com/workers/examples/protect-against-timing-attacks).
