### ISSUE TITLE
Code tags can be escaped by the assistant when dealing with code examples inside of the code itself. 

### ISSUE THREAD

**Issue by Honkychunkymonkey** [enricoros/big-agi#161]
I'm making this issue to discuss the issue of sometimes when the assistant is replying, its replies can escape the code tags its message was previously in. 
![image](https://github.com/enricoros/big-agi/assets/87286565/818d0a89-c9b7-45a2-851f-e415e8a4d2a3)

In the above image it shows that when some code is inside other pieces of code, it can escape its own code tags. Here's the current frontend to see what's happening:

![image](https://github.com/enricoros/big-agi/assets/87286565/df1b0245-47cb-4a9e-b262-18013497f9bd)

**Comment by enricoros** [comment]
Thanks for reporting @Honkychunkymonkey - this is really hard to implement. Markdown blocks can contain more markdown blocks inside.. in this case the "\`\`\`" is the separator that creates issues. I wonder what's the solution to this.

Right now the issue is that a "\`\`\` .... \`\`\`" block is assumed to be top-level and not have other blocks inside. for instance, something like: ... \`\`\` ... \`\`\` ... \`\`\` ... \`\`\` ... could be 2 separate code blocks, or 1 code block within 1 code block. Very hard problem to solve.
