### ISSUE TITLE
ChatGPT Imported shared url = 403 forbidden?

### ISSUE THREAD

**Issue by centminmod** [enricoros/big-agi#165]
I just updated my Big AGI instance running on Cloudflare Pages to latest version at commit https://github.com/enricoros/big-agi/commit/5272fa972a5b1908339f412ec1872ea892734c79

I tried importing a shared ChatGPT Plus link and I get 403 forbidden message?

```
Issues importing 1 conversation:

chatgpt
: [Issue] ChatGPT Importer Forbidden (403) - is https://chat.openai.com/share/XXXXXXXXX accessible by the server?
```

![image](https://github.com/enricoros/big-agi/assets/5899584/dcb9b57f-a2e3-4bdb-8a60-66076f82ef11)

**Comment by enricoros** [comment]
Works locally (see below) but not once deployed. I believe OpenAI servers may be stopping remote access to prevent bots of sorts. The error is a 403.

## Local works
For instance, if I import: https://chat.openai.com/share/6feb31c9-6514-4021-a8fe-bd104a53fe8d
I get:
![image](https://github.com/enricoros/big-agi/assets/32999/09a81896-5023-46ba-88cc-25c86d510b14)

## Remote - on get.big-agi.com:
![image](https://github.com/enricoros/big-agi/assets/32999/6420b5c9-3c96-4293-8eea-9d39e3eb0d8c)

One potential solution is to do this on the client-side, instead of the server side. Ideas?

**Comment by tmikaeld** [comment]
They've added captchas locked to user agent and ip, only way is to use API key

**Comment by enricoros** [comment]
> They've added captchas locked to user agent and ip

Oh no way. Lame. Any ideas on working this around?

**Comment by enricoros** [comment]
@centminmod Fixed in the latest commit - hopefully they won't stop the import again

![image](https://github.com/enricoros/big-agi/assets/32999/314e5da3-9006-4ba1-8e7a-cf6164f139fc)
.
