### ISSUE TITLE
[Feature Request] Image uploads for gpt-4-vision-preview

### ISSUE THREAD

**Issue by jobpaardekooper** [enricoros/big-agi#183]
Would be great if we would be able to select gpt-4-vision-preview and upload images to it.

**Comment by saliksik** [comment]
I don't think he will support GPT-4 vision, TTS, and DALL-E; he made it clear on Discord. My theory is that he is working for Prodia, Elevenlabs, etc., which will directly compete with OpenAI models.

**Comment by Honkychunkymonkey** [comment]
> I don't think he will support GPT-4 vision, TTS, and DALL-E; he made it clear on Discord. My theory is that he is working for Prodia, Elevenlabs, etc., which will directly compete with OpenAI models.

unless you're midjourney, you're not competing with openai.

**Comment by enricoros** [comment]
> I don't think he will support GPT-4 vision, TTS, and DALL-E; he made it clear on Discord. My theory is that he is working for Prodia, Elevenlabs, etc., which will directly compete with OpenAI models.

Haha not at all - but I love your theory. The roadmap is now open and the items for GPT-4 vision and Dall-E have been added. Would love if anyone else contributed code.

Let me tell you the reasons to support or not GPT-4 Vision or Dall-E. Given the huge scope (https://github.com/users/enricoros/projects/4) we have to pick and choose. Professionally I like to work on new and distinctive features, as Dall-E or Vision are available on chatgpt (but notice that the coolest applications happen through APIs).

The work for "catching up" is huge, because we have 7 vendors to build abstractions for once OpenAI overloads their APIs.

If we get a patch for Dall-E or GPT4-Vision today, I promise I won't sleep until it's merged, but in the meantime there's a huge roadmap :D

**Comment by enricoros** [comment]
Closing this request, as it's been broken down into the different parts, with requirements spelled out in the individual tickets: 
 - #215 
 - #212 

If you want TTS, please contribute a ticket (the quality is much lower than Play.ht or competitors at the moment.
