### ISSUE TITLE
Issue with the OpenAI Moderation Servers

### ISSUE THREAD

**Issue by lincolnlyj** [enricoros/big-AGI#322]
### Device and Browser Information

Device: Macbook
OS: MacOS 14.2
Browser: All browser encounters the same issue

### Describe the bug

I always met with the following issue and could not get any response when using big-AGI:
 There was an error while checking for harmful content. TRPCClientError: Error: [Issue] OpenAI/openai: Service Unavailable (503) - 当前分组 default 下对于模型 text-moderation-latest 无可用渠道
But there's no problem when applying the api with python, are there any solution to this problem?

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
Hi @lincolnlyj - the "moderation" API is giving an error, but can be disabled by the UI. It's used to check for harmful content.

The issue is that the OpenAI service is unavailable on the "text-moderation-latest" model. _OpenAI Server Issue_. **Please just disable the Moderation API while the issue persists**.

### Disabling Moderation API
 - Go to `Preferences > Models > OpenAI` > **Advanced**
 - Turn off the "Moderation" button
 - ![image](https://github.com/enricoros/big-AGI/assets/32999/55e40fda-c8e5-4608-b683-acd869bd15ec)

**Comment by lincolnlyj** [comment]
It's solved, thanks a lot for your help
