### ISSUE TITLE
Prompt Issue: OpenRouter flags self-harm

### ISSUE THREAD

**Issue by johnfelipe** [enricoros/big-AGI#352]
### Description

https://github.com/enricoros/big-AGI/assets/428820/c005a425-bcf3-4680-b4b6-3d110208deb8

### Device and browser

https://github.com/enricoros/big-AGI/assets/428820/c005a425-bcf3-4680-b4b6-3d110208deb8

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
Hi @johnfelipe , the title is about a warning from the Zustand library, that is there only to help developers and has no influence to any bug.

The video is about the absence of "moderation" when calling gpt-4-32k.

Can you open the Model > OpenAI > Advanced options, enable "Moderation" and try again?

OpenAI must have changed the requirements for gpt-4-32k. 

Please try with Moderation on (as the OpenAI message says) and let me know.

**Comment by enricoros** [comment]
Hi @johnfelipe what I see on the video is the OpenRouter service rejecting the prompt because it classifies it as "self-harm" category (probably a false positive).

This is why OpenRouter is not producing the answer. The console message is something completely different and unrelated and expected. Please let me know if there's any other issue or we'll close this.

**Comment by johnfelipe** [comment]
https://github.com/enricoros/big-AGI/assets/428820/b46deee0-1bc3-4bf4-aef4-087187eb2b9f

not working, pls review video

**Comment by enricoros** [comment]
> SNAG-0030.mp4 
> not working, pls review video

Yes, I see the video. Try changing to the "⭐ 4-Turbo (1106)" network, from OpenAI, and disable the Moderation in Models > OpenAI. It should work!

![image](https://github.com/enricoros/big-AGI/assets/32999/24f571a0-8e08-464d-9bf7-f9df84fbdab4)

The issue is that the text you send seems to contain "self-harm" material.

**Comment by johnfelipe** [comment]
i solve using palm, tnks for steps
