### ISSUE TITLE
[Roadmap] Add Replicate support and API configuration option

### ISSUE THREAD

**Issue by eshack94** [enricoros/big-AGI#357]
**Why**
This allows users to have more options for experimenting with new tools and models from the Replicate provider using their API key.

**Description**
Add option for supplying Replicate API key on configuration screen. Add other support as necessary to support Replicate models.

On the "Configure API Keys" pop-up, an option exists for configuring with Replicate (https://replicate.com/).

**Requirements**
Unsure what technical requirements this would entail. I am not that familiar with this code base.

**Comment by enricoros** [comment]
Thanks - to prioritize support, which kind of Replicate APIs (pictures, text..) are important to you?

I see Generate images, Generate text, Generate videos, Generate music, Generate speech, Fine tune models, Restore images, and this requires probably weeks to get it all done. 

Please provide a prioritization of the functions/networks, or examples of the top uses, as supporting "all' is not an option given the amount of requests we have.

**Comment by enricoros** [comment]
Closed - missing info from the requester

**Comment by JNuno007** [comment]
HI @enricoros, using this issue to ask if there is a way to use the replicate API to access ollama models instead of hosting them locally?

If not, could we have something like a custom API option where we add the necessary header keys and values, and also the payload (with temperatures and pre prompts and so on)?

Reference to Replicate's Ollama API: https://replicate.com/meta/meta-llama-3-70b-instruct/api

Thanks for this amazing project! Cheers

**Comment by enricoros** [comment]
Hi @JNuno007 , in principle yes this is doable in that way. In case of replicate we'll also need a custom prompt template builder and then output parser, but definitely doable. I don't have the bandwidth to take on this task myself, but I'll accept a pull request that provided a robust implementation of this.
