### ISSUE TITLE
Is there a way to disable GPT-4 models?

### ISSUE THREAD

**Issue by haopengsong** [enricoros/big-AGI#378]
And only allow calls to GPT-3.5. THX.

**Comment by enricoros** [comment]
There's an easy way of doing this, which would be to filter the models on the backend when the user issues a refresh (Update Models) request.

In the OpenAI backend files, listModels function, a restriction could be applied. However, it's harder to link to an env variable, and may require code changes. Opinions?

**Comment by haopengsong** [comment]
Wow, this works very well, just put some filtering logic within the switch statement for case openai and it worked. THanks!

**Comment by enricoros** [comment]
> Wow, this works very well, just put some filtering logic within the switch statement for case openai and it worked. THanks!

Glad to hear! Making it generic for everyone would require some work and documentation, so I'm happy that you can maintain a smaller patch in your branch.

Are there other features you need to maintain on the branch? I can evaluate to see if some can be better done upstream to reduce the burden of maintaining them. Otherwise back to work, there is SO much on the roadmap!

**Comment by haopengsong** [comment]
Thanks for the generosity. So far so good for now. 
The only feature I tried to implement last week was to add an authentication mechnism with NextAuth so that users can do login and there would be logs in Postgres or similiar, however I didn't make it because there were config related compactible issues which I can't resolve for now. Please let me know if there will be more authentication features coming out later.

**Comment by enricoros** [comment]
Thanks. Closing as support for Auth requires a separate ticket.

The tracking for Auth right now is #160 - we had experiments for Auth, but can't deploy it yet to the base product, as everyone will have to configure authentication backends for all of their Big-AGI installation. That said, I believe sooner rather than later we'll need it.

In the meantime, take a look at [docs/deploy-authentication.md](https://github.com/enricoros/big-AGI/blob/main/docs/deploy-authentication.md)
