### ISSUE TITLE
[BUG] LocalAI API KEY

### ISSUE THREAD

**Issue by lunamidori5** [enricoros/big-AGI#432]
### Description

Needs a place to put API Key for localai for self hosted copies that use API keys. follows openai standard

### Device and browser

All Device types

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by lunamidori5** [comment]
I mean I could contribute if I knew how

**Comment by lunamidori5** [comment]
![image](https://github.com/enricoros/big-AGI/assets/118759930/315d6afa-edcf-4193-9fba-1584fab2a3a8)

**Comment by lunamidori5** [comment]
> @lunamidori5 Thanks for letting me know - do you know if it's the same Authentication: Bearer... header?

@enricoros yes it follows openai standards

**Comment by lunamidori5** [comment]
@enricoros please take your time! Was thinking I report it just incase

**Comment by enricoros** [comment]
Thanks @lunamidori5 - I believe on `main` this is now fixed.

Would you be able to confirm if it works? I don't have a setup protected with key at the moment.

Additionally, I made it so that when running big-AGI (via node, or docker), LocalAI can be configured using:
 - LOCALAI_API_HOST: host (shall work well with docker hosts)
 - LOCALAI_API_KEY: the key to be used for all requests

Backend keys are not visible in the UI, but the UI can at any time override backend keys.
Thanks for reporting.

**Comment by lunamidori5** [comment]
Ill have to wait for the docker update but thank you for all your hard work!

**Comment by enricoros** [comment]
Happy to help. The development docker should be updated now.
