### ISSUE TITLE
Docker big-AGI and OLLAMA integration issue

### ISSUE THREAD

**Issue by Shadow-Wizard-Money-Gang** [enricoros/big-AGI#440]
### Description

I had the netwrok error previsouly on https://github.com/enricoros/big-AGI/issues/276 and I tried their solutions and am now running big-AGI in a docker container and ollama locally, how do I connect them though as I am now getting a new error: [Issue] Ollama: (network) fetch failed - Error: connect ECONNREFUSED 127.0.0.1:11434

### Device and browser

On windows 11 on firefox latest version

### Screenshots and more

![image](https://github.com/enricoros/big-AGI/assets/130067591/4e2fd45a-8778-4d5a-a316-14b28bababc2)
![image](https://github.com/enricoros/big-AGI/assets/130067591/85ea24a2-0c21-4f8f-8e88-3ead60f6d4fb)

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
If big-agi is running in a container (an isolated network) and Olama locally, then big-AGI cannot contact Olama.

This is shown partially in this section: https://github.com/enricoros/big-AGI/blob/main/docs/config-local-ollama.md#%EF%B8%8F-network-troubleshooting

The core of the issue is a docker network configuration issue and not a bug in big-AGI.

If you look at the docs/config-browse file, there's an example Docker file to run two containers that can both see each other. Maybe that's a solution that can work for you?

**Comment by Opswatch** [comment]
Use this as the address for ollama  host.docker.internal plus the ollama port and it should work.

**Comment by Gameon666** [comment]
yep indeed it has solved the issue, thank you.
![ollama docker issue solved](https://github.com/enricoros/big-AGI/assets/105184788/3e21433a-3f46-410e-8e91-30554ccc9ea1)
