### ISSUE TITLE
[BUG] Can't connect to LM Studio on https://get.big-agi.com/

### ISSUE THREAD

**Issue by rikyotei** [enricoros/big-AGI#467]
### Description

![图片](https://github.com/enricoros/big-AGI/assets/16711623/c8e6d22c-d14e-430a-8c8f-eea6b1aa788d)
I got this error on https://get.big-agi.com/
Can you please take look this?

This problem does not exist when I run the project locally. By the way, i have already enabled CROS. I think it is not a CROS problem.

I have also run debug in broswer, there is no any request to http://localhost:1234 when i click models button.

### Device and browser

windows 11, chrome

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
Yes the issue here (fully expected) is that it is the Backend of Big-AGI that's trying to connect to LM Studio.

When you run locally, the front end and back end are both running on localhost. But when you run that official website the backend is running on Vercel servers, while the frontend is on the browser (localhost).

So then the back end, which is running in some server somewhere will be trying to connect to a port on its own "localhost", and it fails because LM Studio is running on your computer.

Please take a look at https://github.com/enricoros/big-AGI/issues/276#issuecomment-1858591483 for the same issue, with a description and a diagram.

**Comment by rikyotei** [comment]
> Yes the issue here (fully expected) is that it is the Backend of Big-AGI that's trying to connect to LM Studio.
> 
> When you run locally, the front end and back end are both running on localhost. But when you run that official website the backend is running on Vercel servers, while the frontend is on the browser (localhost).
> 
> So then the back end, which is running in some server somewhere will be trying to connect to a port on its own "localhost", and it fails because LM Studio is running on your computer.
> 
> Please take a look at [#276 (comment)](https://github.com/enricoros/big-AGI/issues/276#issuecomment-1858591483) for the same issue, with a description and a diagram.

@enricoros Thank you for your help.

**Comment by PylotLight** [comment]
> > Yes the issue here (fully expected) is that it is the Backend of Big-AGI that's trying to connect to LM Studio.
> > When you run locally, the front end and back end are both running on localhost. But when you run that official website the backend is running on Vercel servers, while the frontend is on the browser (localhost).
> > So then the back end, which is running in some server somewhere will be trying to connect to a port on its own "localhost", and it fails because LM Studio is running on your computer.
> > Please take a look at [#276 (comment)](https://github.com/enricoros/big-AGI/issues/276#issuecomment-1858591483) for the same issue, with a description and a diagram.
> 
> @enricoros Thank you for your help.

If you served your lm studio api endpoint publicly via ngrok you might be able to get it to work btw.
