### ISSUE TITLE
Allow modification of context length for Ollama - [Roadmap]

### ISSUE THREAD

**Issue by kunchenwork** [enricoros/big-AGI#495]
**Why**
Context length is a key trait in utilising LLM If we implement this, users would be able to change the context length for models capable of doing so, making big-AGI much more powerful to handle long text.

**Description**
 Ollama allow API calls to specify context length. [(see Ollama FAQ)](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-can-i-specify-the-context-window-size)
Can we add the context length setting for Ollama local models.

**Requirements**
- [UX] add a slide bar to modify context length for different Ollama model
- [API Calls] modify the api calls to local ollama server to use context length as a parameter input from user setting

**Comment by kunchenwork** [comment]
Hi @enricoros. Thanks for the prompt response. To clarify, I am referring to the context length, which is set to 4096 by default for every model even though some of them can handle more. Take the Mistral as an example, the mistral v0.2 can handle 32k context, but it only shows 4k context limit in the model configuration page.
<img width="684" alt="image" src="https://github.com/enricoros/big-AGI/assets/34080178/01b64bf0-fe81-4693-ad5e-e55373cf6860">

**Comment by enricoros** [comment]
Hi @kunchenwork, I've researched and this is the conclusion. This issue came up before: #309 

I posted this detailed comment on the Ollama GitHub a couple of months ago, requesting for Ollama to declare the Context Size of the models: https://github.com/ollama/ollama/issues/1473#issuecomment-1909046525

Analysis results:
- Adding the context window in the API is is not done yet (see ticket)
- The "tags" API, which list models, does not report Context Window information:
![image](https://github.com/enricoros/big-AGI/assets/32999/9eb3ba13-6e79-467c-a954-aac624a6c721)
- The "show" API, which lists model details, reports context window information only on very few models (I tried many):
![image](https://github.com/enricoros/big-AGI/assets/32999/2d50929c-3899-44d8-9b6c-e2afe0f1f5a7)
- The commandline API that you mention, is during a CLI session with ollama, so UIs cannot see it

As per the analysis, in this example for Mistral-7B (the one you used), Ollama does not report the context window.

**Comment by enricoros** [comment]
Closing until Ollama fixes this. Very detailed analysis provided.

**Comment by enricoros** [comment]
Here's why: Ollama is a large and funded project with lots of contributors. If the project provided the context length of models, every UI will just work great.

I could also add an option to override it, but unfortunately it's not high on my priority list to add workarounds, so I personally cannot do it, but I welcome and I will merge any contribution to Big-AGI that allows a manual override of the context length (it's also not hard, but I have 100 bugs before this, in line).

My advice is to go to ask Ollama for having a correct reporting of the number of tokens per model, which is the right solution that scales across the ecosystem.

**Comment by arsaboo** [comment]
I totally understand that there may be other pressing issues. Would you be open to adding `contextWindow` information to the model files (like you have for Anthropic and other models)?

**Comment by enricoros** [comment]
Note @arsaboo , @kunchenwork , if Ollama does not specify the num_ctx parameter (as it should) and the model list does not contain tokens (as I've requested), there's the option to change the list of models manually (no UI) as per #518

**Comment by arsaboo** [comment]
@enricoros This works for now. Given that there will not be TON of models, we can keep it updated manually if we have to.
