### ISSUE TITLE
[BUG] Beam-compare (fusion) bug

### ISSUE THREAD

**Issue by Playerrrrr** [enricoros/big-AGI#529]
### Description

if I dont press 2x/4x/8x and just **_manually add models_**, generate for eg 4x responses it seems the beam “compare” feature does not work properly(?) and generates hallucinating answers in the fusion-compare (r1,r2,r3,r4 comparison) 

Also when putting Response 1, 2 ,3 ,4 it would be better if it would point at the exact response, as its a pain in the ass to read the comparisons and try to guess in which order is it talking about the answers.

### Device and browser

Macbook Pro M2

**Comment by enricoros** [comment]
There's a "show response numbers" option in the "..." menu, which will help with the identification of the response numbers.

![image](https://github.com/enricoros/big-AGI/assets/32999/455f1862-424f-4863-a355-f37dc9bb5632)

There's a weak link to the responses because by the time the Comparison has finished, there's a chance the user has deleted/moved/regenerated the response, so there's that to consider. The UI will have to be much more dynamic, at this time, to accomodate for a better implementation.

You will hopefully find the next version of Beam (to be released in hours) to be more UX friendly already.
