### ISSUE TITLE
In-line Free Scroll toggling 

### ISSUE THREAD

**Issue by jondwillis** [enricoros/big-AGI#59]
A common UX affordance is to enable free scroll and add a “⬇️ scroll to bottom” floating action button that disables free scroll. optionally, this new behavior could be disabled with another setting/env var.

**Comment by enricoros** [comment]
Just tested this. A bit tough at the edges, but should be the default. Will need to do some cleanup, but thanks for the patch!

**Comment by enricoros** [comment]
I admit the FAB is not there yet - and the scrolling is just okay, sometimes on mobile is not optimal. The browser-standard way of doing it, is to use a flexbox with row-reverse as the display mode. So that the message[0] is at the bottom and browsers go to it.

However one day we may re-migrate to the 'scrollToBottom()' way of doing it every time there's a new token..
