### ISSUE TITLE
[BUG] Haiku 3.5 Model missing

### ISSUE THREAD

**Issue by Kim2091** [enricoros/big-AGI#692]
### Description

https://www.anthropic.com/claude/haiku

Haiku 3.5 was released last month, and it's a noticeable improvement at the same cost as Haiku 3.0.

It seems to be missing from big-AGI

### Device and browser

Windows 11
Firefox 133.0

### Screenshots and more

![image](https://github.com/user-attachments/assets/5c39bf38-d2ec-416d-ac88-8d1a0ab61ea7)

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
@Kim2091 if this is the big-agi.com website, you just need to "Update Models". You can go to Preferences > Models and update Anthropic, or to the Model Switcher (top bar) and update.

If this is your own code build, you have to update the code (and I assume you are using the `v2-dev` branch). The reason is that Anthropic doesn't have a models list API, leaving it to developers to "hardcode" the models in their code.

**Comment by Kovah** [comment]
I have the same issue. Using 1.16.9 I only get the 3.5 Sonnet model, but 3.5 Haiku is not available. Using my own self-hosted version, but it's also not working on the officially hosted one.

There is [an API endpoint](https://docs.anthropic.com/en/api/models-list) for getting models and I tried to get models using my API key. Haiko 3.5 is in there.

```
{
  "data": [
    {
      "type": "model",
      "id": "claude-3-5-sonnet-20241022",
      "display_name": "Claude 3.5 Sonnet (New)",
      "created_at": "2024-10-22T00:00:00Z"
    },
    {
      "type": "model",
      "id": "claude-3-5-haiku-20241022",
      "display_name": "Claude 3.5 Haiku",
      "created_at": "2024-10-22T00:00:00Z"
    },
    ...
  ]
}
```
