### ISSUE TITLE
[Roadmap] Allow mapping AI Personas to OpenAI Assistants

### ISSUE THREAD

**Issue by atxcowboy** [enricoros/big-AGI#707]
**Why**
By allowing users to create and map custom AI personas to their predefined OpenAI assistants, big-AGI v2 would enable tailored experiences that align with individual preferences and specific use cases. This feature moves beyond the rather generic AI assistants, providing users with assistants that can perform file searches, interpret code and reference third party APIs via the function calling of openai.

**Description**
Introduce a feature in big-AGI v2 that allows users to map AI personas to an existing OpenAI assistant. 

**Requirements**
It would be nice to define the assistant ID similar to the elevenLabs voiceId in src/data.ts.
The assistants api could be used for that purpose (https://platform.openai.com/docs/assistants/tools).

**Comment by enricoros** [comment]
OpenAI assistants have a very hard API that only works with OpenAI models (while big agi needs to support any model).

Won't be able to tackle this, very likely. There are a number of limitations (expiration of files and threads, etc).

This will induce a Large vendor lock-in to big agi, only for OpenAI, making it impossible to migrate those personas to Anthropic or Google.  Not sure there's an easy solution.

**Comment by enricoros** [comment]
Since supporting the OpenAI Assistants API will make Big-AGI non vendor-neutral, making the product what it's not meant to be and introducing limitations, I'll park this request.

Once the Assistants API is out of Beta (OpenAI still has it in beta, and changed before) and we understand the implication of having the chats/threads/runs/assistants all hosted on OpenAI servers, with slowness, lack of authority, control, etc - then I will reopen it.
